name: Koboldcpp Builder Windows Full Binaries

on: workflow_dispatch
env:
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}

jobs:
  windows:
    runs-on: windows-2019
    steps:
      - name: Clone
        id: checkout
        uses: actions/checkout@v3
        with:
          ref: concedo_experimental

      - name: Get Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8.10

      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install customtkinter==5.2.0 pyinstaller==5.11.0 psutil==5.9.5

      - name: Download and install win64devkit
        run: |
          curl -L https://github.com/skeeto/w64devkit/releases/download/v1.22.0/w64devkit-1.22.0.zip --output w64devkit.zip
          Expand-Archive w64devkit.zip -DestinationPath .

      - name: Add w64devkit to PATH
        run: |
          $env:Path += ";$(Get-Location)\w64devkit-1.22.0\w64devkit\bin"
          echo $env:Path
          ls

      - name: Build Non-CUDA
        id: make_build
        run: |
          make -j ${env:NUMBER_OF_PROCESSORS}
          ls

      # - uses: Jimver/cuda-toolkit@v0.2.11
      #   id: cuda-toolkit
      #   with:
      #     cuda: '11.4.4'

      # - name: Build CUDA
      #   id: cmake_build
      #   run: |
      #     mkdir build
      #     cd build
      #     cmake .. -DLLAMA_CUBLAS=ON -DCMAKE_SYSTEM_VERSION="10.0.19041.0"
      #     cmake --build . --config Release -j ${env:NUMBER_OF_PROCESSORS}

      # - name: Save artifact
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: kcpp_windows_cuda_binary
      #     path: build/bin/Release/
